// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request.proto

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	request.proto
	response.proto

It has these top-level messages:
	Request
	Response
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Id            string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Method        string   `protobuf:"bytes,2,opt,name=method" json:"method,omitempty"`
	Endpoint      string   `protobuf:"bytes,3,opt,name=endpoint" json:"endpoint,omitempty"`
	Headers       []string `protobuf:"bytes,4,rep,name=headers" json:"headers,omitempty"`
	ResponseQueue string   `protobuf:"bytes,5,opt,name=response_queue,json=responseQueue" json:"response_queue,omitempty"`
	Body          string   `protobuf:"bytes,6,opt,name=body" json:"body,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Request) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *Request) GetHeaders() []string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *Request) GetResponseQueue() string {
	if m != nil {
		return m.ResponseQueue
	}
	return ""
}

func (m *Request) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "protobuf.Request")
}

func init() { proto.RegisterFile("request.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8e, 0x4b, 0xaa, 0xc2, 0x50,
	0x0c, 0x40, 0xe9, 0xe7, 0xf5, 0x13, 0x68, 0x07, 0x19, 0x3c, 0x82, 0xa3, 0x22, 0x08, 0x1d, 0x39,
	0x71, 0x25, 0x76, 0x03, 0x62, 0xb9, 0x91, 0x76, 0x60, 0x73, 0x7b, 0x3f, 0x03, 0xb7, 0xe3, 0x4a,
	0xc5, 0x68, 0x1d, 0x25, 0xe7, 0x1c, 0x02, 0x81, 0xc6, 0xf1, 0x1a, 0xd9, 0x87, 0xa3, 0x75, 0x12,
	0x04, 0x2b, 0x1d, 0x63, 0xbc, 0xed, 0x9f, 0x09, 0x94, 0xc3, 0xa7, 0x61, 0x0b, 0xe9, 0x6c, 0x28,
	0xe9, 0x92, 0xbe, 0x1e, 0xd2, 0xd9, 0xe0, 0x3f, 0x14, 0x77, 0x0e, 0x93, 0x18, 0x4a, 0xd5, 0x7d,
	0x09, 0x77, 0x50, 0xf1, 0x62, 0xac, 0xcc, 0x4b, 0xa0, 0x4c, 0xcb, 0x8f, 0x91, 0xa0, 0x9c, 0xf8,
	0x6a, 0xd8, 0x79, 0xca, 0xbb, 0xac, 0xaf, 0x87, 0x0d, 0xf1, 0x00, 0xad, 0x63, 0x6f, 0x65, 0xf1,
	0x7c, 0x59, 0x23, 0x47, 0xa6, 0x3f, 0xbd, 0x6d, 0x36, 0x7b, 0x7e, 0x4b, 0x44, 0xc8, 0x47, 0x31,
	0x0f, 0x2a, 0x34, 0xea, 0x3e, 0x16, 0xfa, 0xee, 0xe9, 0x15, 0x00, 0x00, 0xff, 0xff, 0xd9, 0x2d,
	0x50, 0x0a, 0xc6, 0x00, 0x00, 0x00,
}
